ARG IMAGE_TAG="3.14.2-slim-trixie"
FROM python:$IMAGE_TAG AS builder

ARG POETRY_VERSION=2.2.1
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_NO_INTERACTION=1
ENV POETRY_CACHE_DIR=/tmp/poetry_cache

COPY pyproject.toml poetry.lock ./

RUN pip install --no-cache-dir "poetry==$POETRY_VERSION" && \
    poetry install --no-root --with test

FROM python:$IMAGE_TAG AS runner

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONFAULTHANDLER=1
ENV BINPATH="/usr/local/bin"
ENV PYTHONPATH="/usr/local/lib/python3.14/site-packages"
ENV APP_PATH=/app

RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

COPY --from=builder /usr/local/lib/python3.14/site-packages ${PYTHONPATH}
COPY --from=builder /usr/local/bin/alembic ${BINPATH}/alembic
COPY --from=builder /usr/local/bin/uvicorn ${BINPATH}/uvicorn
COPY --from=builder /usr/local/bin/pytest ${BINPATH}/pytest
COPY alembic.ini pyproject.toml ./
COPY src src
COPY tests tests

WORKDIR $APP_PATH

ENTRYPOINT ["pytest"]
