"""add

Revision ID: edacbfe9a66c
Revises: 661cbb626298
Creation Date: 2026-04-07 01:34:16.322850
"""

from typing import (
    Sequence,
    Union,
)

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dc22fe720ed"
down_revision: Union[str, Sequence[str], None] = "661cbb626298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("device_type", sa.SmallInteger(), nullable=False),
        sa.Column("width", sa.SmallInteger(), nullable=False),
        sa.Column("height", sa.SmallInteger(), nullable=False),
        sa.Column("user_agent", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("devices_profiles", sa.Column("template_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_devices_profiles_template_id"), "devices_profiles", ["template_id"], unique=False)
    op.create_foreign_key(None, "devices_profiles", "device_templates", ["template_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devices_profiles", type_="foreignkey")
    op.drop_index(op.f("ix_devices_profiles_template_id"), table_name="devices_profiles")
    op.drop_column("devices_profiles", "template_id")
    op.drop_table("device_templates")
    # ### end Alembic commands ###
