"""add user_id - device relationship

Revision ID: 661cbb626298
Revises: 770b370dff40
Creation Date: 2026-04-05 23:28:44.631934
"""

from typing import (
    Sequence,
    Union,
)

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "661cbb626298"
down_revision: Union[str, Sequence[str], None] = "770b370dff40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices_profiles", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_devices_profiles_user_id"), "devices_profiles", ["user_id"], unique=False)
    op.create_foreign_key(None, "devices_profiles", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "devices_profiles", type_="foreignkey")
    op.drop_index(op.f("ix_devices_profiles_user_id"), table_name="devices_profiles")
    op.drop_column("devices_profiles", "user_id")
    # ### end Alembic commands ###
