class BaseDeviceError(Exception): ...


class DeviceProfileNotFoundError(BaseDeviceError): ...


class DeviceTemplateNotFoundError(BaseDeviceError): ...


class TemplateNameAlreadyExistsError(BaseDeviceError): ...
